version: '3.3'

services:
  app:
    image: $DOCKER_IMAGE
    environment: &environment
      MYSQL_HOST:
      MYSQL_DATABASE:
      MYSQL_USERNAME:
      MYSQL_PASSWORD:
      WP_HOME:
      WP_SITEURL:
    volumes:
      - .:/app
    ports:
      - "30000:80"

  cmd:
    image: $DOCKER_IMAGE
    environment: *environment
    healthcheck:
      disable: true
